### ISSUE TITLE
A comment from a user

### ISSUE THREAD

**Issue by aobaz** [aisharaf/rms#103]
Dear Dr
I submitted my project no. 15-SCI-3-1-0001 but the system did not give me the full file. The system has a problem. Please, solve this problem and send to me the full version of my project.
Thank you
Prof. Dr. HAMDY M. YOUSSEF
FACULTY OF ENGINEERING, P. O. 5555
UMM AL-QURA UNIVERSITY,
MAKKAH,
SAUDI ARABIA

**Comment by abdelghafar** [comment]
this is the error 
Forbidden

You don't have permission to access /dsr/rms/Researchers/<b>FPDF error:</uploads/22/consultant_agreement_5065.pdf) probably uses a compression technique which is not supported by the free parser shipped with FPDI. on this server.

Apache/2.2.4 (Win32) PHP/5.2.3 Server at localhost Port 80

**Comment by abdelghafar** [comment]
his project has been reopened 
he should upload consultant agreement pdf file without using any compression technique and submit the project again
