### ISSUE TITLE
add to about page after the first paragraph and before the support statement

### ISSUE THREAD

**Issue by aobaz** [aisharaf/rms#110]
فريق العمل
الإشراف العام والتنسيق: عميد البحث العلمي د.فيصل بن احمد علاف
الإشراف المباشر والتحليل وتحديد أعمال وتقنيات النظام: وكيل عمادة البحث العلمي للمعلومات والنشر د.عبدالله بن عمر باز
فريق التطوير: د. السيد رضوان, أ.احمد شرف, أ.عبدالغفار هادي

**Comment by abdelghafar** [comment]
Done
