### ISSUE TITLE
users table alert

### ISSUE THREAD

**Issue by aisharaf** [aisharaf/rms#120]
https://gist.github.com/aisharaf/d94f0e2c71a803f6361e

**Comment by abdelghafar** [comment]
DROP TABLE IF EXISTS `reseach_status`;
CREATE TABLE `reseach_status` (
  `Status_Id` int(11) NOT NULL auto_increment,
  `Status_name` varchar(100) NOT NULL,
  `Phase_id` int(2) NOT NULL,
  PRIMARY KEY  (`Status_Id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

-- 
-- Dumping data for table `reseach_status`
-- 

INSERT INTO `reseach_status` VALUES (1, 'تم الاستلام', 1);
INSERT INTO `reseach_status` VALUES (2, 'قيد الفحص', 1);
INSERT INTO `reseach_status` VALUES (3, 'منجزة بالرفض', 1);
INSERT INTO `reseach_status` VALUES (4, 'مقبول ومحال للتحكيم', 1);
INSERT INTO `reseach_status` VALUES (5, 'قيد التحكيم', 2);
INSERT INTO `reseach_status` VALUES (6, 'لا أوصي بالتمويل', 2);
INSERT INTO `reseach_status` VALUES (7, 'أوصي بالتمويل دون أي تعديل', 2);

-- --------------------------------------------------------

-- 
-- Table structure for table `sys_rules`
-- 

DROP TABLE IF EXISTS `sys_rules`;
CREATE TABLE `sys_rules` (
  `rule_id` int(11) NOT NULL auto_increment,
  `rule_name` varchar(255) NOT NULL,
  `url` varchar(512) NOT NULL,
  `rule_desc` varchar(512) NOT NULL,
  PRIMARY KEY  (`rule_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=9 ;

-- 
-- Dumping data for table `sys_rules`
-- 

INSERT INTO `sys_rules` VALUES (1, 'DSRDean', '', 'لوحة تحكم عمادة البحث
العلمي');
INSERT INTO `sys_rules` VALUES (2, 'DSRVIT', '', 'لوحة تحكم وكيل البحث
العلمي للمعلومات');
INSERT INTO `sys_rules` VALUES (3, 'DSRVPG', 'DSRVPG/index.php', 'لوحة تحكم
وكيل البحث العلمي للمنح البحثية');
INSERT INTO `sys_rules` VALUES (4, 'DSRVSC', '', 'لوحة تحكم وكيل البحث
العلمي للكراسي العلمية');
INSERT INTO `sys_rules` VALUES (5, 'DSRVSI', '', 'لوحة تحكم وكيل البحث
العلمي للنزاهة العلمية');
INSERT INTO `sys_rules` VALUES (6, 'DSRVFM', '', 'لوحة تحكم وكيل البحث
العلمي شطر الطالبات');
INSERT INTO `sys_rules` VALUES (7, 'DSRVPG_SupportTeam',
'DSRVPG_SupportTeam/index.php', 'لوحة تحكم فريق الدعم لوكيل البحث العلمي
للمنح');
INSERT INTO `sys_rules` VALUES (8, 'reviewer', 'Reviewer/index.php', 'لوحة
تحكم المحكمين');

-- --------------------------------------------------------

-- 
-- Table structure for table `users`
-- 

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL auto_increment,
  `user_name` varchar(50) NOT NULL,
  `pass` varchar(100) NOT NULL,
  `activation_code` varchar(32) NOT NULL,
  `person_id` int(11) NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `sys_rule_id` int(2) NOT NULL,
  `from_date` date NOT NULL,
  `thru_date` date NOT NULL,
  `is_temp` tinyint(1) NOT NULL default '0',
  `alias_name` varchar(1024) NOT NULL,
  `last_access` datetime NOT NULL,
  `creation_date` datetime NOT NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `user_name` (`user_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=20 ;

-- 
-- Dumping data for table `users`
-- 

INSERT INTO `users` VALUES (1, 'DSRDean@uqu.edu.sa', '', '', 0, 0, 1,
'0000-00-00', '0000-00-00', 0, 'عميد البحث العلمي', '0000-00-00 00:00:00',
'0000-00-00 00:00:00');
INSERT INTO `users` VALUES (2, 'DSRVIT@uqu.edu.sa', '', '', 0, 0, 2,
'0000-00-00', '0000-00-00', 0, 'وكيل عمادة البحث العلمي للمعلومات والنشر',
'0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `users` VALUES (3, 'DSRVPG@uqu.edu.sa', '', '', 0, 0, 3,
'0000-00-00', '0000-00-00', 0, 'وكيل عمادة البحث العلمي للمنح والمشاريع
البحثيه', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `users` VALUES (4, 'DSRVSC@uqu.edu.sa', '', '', 0, 0, 4,
'0000-00-00', '0000-00-00', 0, 'وكيل عمادة البحث العلمي للكراسي العلمية',
'0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `users` VALUES (5, 'DSRVSI@uqu.edu.sa', '', '', 0, 0, 5,
'0000-00-00', '0000-00-00', 0, 'وكيل عمادة البحث العلمي للنزاهه العلمية',
'0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `users` VALUES (6, 'DSRVFM@uqu.edu.sa', '', '', 0, 0, 6,
'0000-00-00', '0000-00-00', 0, 'وكيلة عمادة البحث العلمي لفرع الطالبات',
'0000-00-00 00:00:00', '0000-00-00 00:00:00');
INSERT INTO `users` VALUES (7, 'dsrmalesupport@uqu.edu.sa', '', '', 0, 0,
7, '0000-00-00', '0000-00-00', 0, 'الدعم الفني رجال', '0000-00-00
00:00:00', '0000-00-00 00:00:00');
INSERT INTO `users` VALUES (8, 'dsrfemalesupport@uqu.edu.sa', '', '', 0, 0,
7, '0000-00-00', '0000-00-00', 0, 'الدعم الفني نساء', '0000-00-00
00:00:00', '0000-00-00 00:00:00');
INSERT INTO `users` VALUES (19, 'aaaa@ddd.net', '5559275cc61ec',
'5559275cc61f2', 3, 1, 8, '0000-00-00', '0000-00-00', 0, '', '0000-00-00
00:00:00', '2015-05-18 01:42:20');


On Mon, May 18, 2015 at 11:15 AM, Ahmed I. Sharaf <notifications@github.com>
wrote:

> -- phpMyAdmin SQL Dump
> -- version 4.1.14
> -- http://www.phpmyadmin.net
>
> -- Host: 127.0.0.1
> -- Generation Time: May 18, 2015 at 10:13 AM
> -- Server version: 5.6.17
> -- PHP Version: 5.5.12
>
> SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
> SET time_zone = "+00:00";
>
> /
> *!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */; /*!40101
> SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS
> */; /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION
> */; /*!40101 SET NAMES utf8 */;
>  -- Database: dsr_rms
> ------------------------------
>  -- Table structure for table users
>
> CREATE TABLE IF NOT EXISTS users (
> id int(11) NOT NULL AUTO_INCREMENT,
> user_name varchar(50) NOT NULL,
> pass varchar(100) NOT NULL,
> activation_code varchar(32) NOT NULL,
> person_id int(11) NOT NULL,
> rule varchar(20) NOT NULL,
> is_active tinyint(1) NOT NULL,
> sys_group_id int(2) NOT NULL,
> from_date date NOT NULL,
> thru_date date NOT NULL,
> is_temp tinyint(1) NOT NULL DEFAULT '0',
> alias_name varchar(1024) NOT NULL,
> last_access datetime NOT NULL,
> creation_date datetime NOT NULL,
> url varchar(255) NOT NULL,
> PRIMARY KEY (id),
> UNIQUE KEY user_name (user_name)
> ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=20 ;
>  -- Dumping data for table users
>
> INSERT INTO users (id, user_name, pass, activation_code, person_id, rule,
> is_active, sys_group_id, from_date, thru_date, is_temp, alias_name,
> last_access, creation_date, url) VALUES
> (1, 'DSRDean@uqu.edu.sa', '', '', 0, 'DSRDean', 0, 0, '0000-00-00',
> '0000-00-00', 0, 'عميد البحث العلمي', '0000-00-00 00:00:00', '0000-00-00
> 00:00:00', ''),
> (2, 'DSRVIT@uqu.edu.sa', '', '', 0, 'DSRVIT', 0, 0, '0000-00-00',
> '0000-00-00', 0, 'وكيل عمادة البحث العلمي للمعلومات والنشر', '0000-00-00
> 00:00:00', '0000-00-00 00:00:00', ''),
> (3, 'DSRVPG@uqu.edu.sa', '', '', 0, 'DSRVPG', 0, 0, '0000-00-00',
> '0000-00-00', 0, 'وكيل عمادة البحث العلمي للمنح والمشاريع البحثيه',
> '0000-00-00 00:00:00', '0000-00-00 00:00:00', ''),
> (4, 'DSRVSC@uqu.edu.sa', '', '', 0, 'DSRVSC', 0, 0, '0000-00-00',
> '0000-00-00', 0, 'وكيل عمادة البحث العلمي للكراسي العلمية', '0000-00-00
> 00:00:00', '0000-00-00 00:00:00', 'Administration'),
> (5, 'DSRVSI@uqu.edu.sa', '', '', 0, 'DSRVSI', 0, 0, '0000-00-00',
> '0000-00-00', 0, 'وكيل عمادة البحث العلمي للنزاهه العلمية', '0000-00-00
> 00:00:00', '0000-00-00 00:00:00', ''),
> (6, 'DSRVFM@uqu.edu.sa', '', '', 0, 'DSRVFM', 0, 0, '0000-00-00',
> '0000-00-00', 0, 'وكيلة عمادة البحث العلمي لفرع الطالبات', '0000-00-00
> 00:00:00', '0000-00-00 00:00:00', ''),
> (7, 'dsrmalesupport@uqu.edu.sa', '', '', 0, 'DSRVPG', 0, 0, '0000-00-00',
> '0000-00-00', 0, 'الدعم الفني رجال', '0000-00-00 00:00:00', '0000-00-00
> 00:00:00', 'Administration'),
> (8, 'dsrfemalesupport@uqu.edu.sa', '', '', 0, 'DSRVPG', 0, 0,
> '0000-00-00', '0000-00-00', 0, 'الدعم الفني نساء', '0000-00-00 00:00:00',
> '0000-00-00 00:00:00', ''),
> (19, 'aaaa@ddd.net', '5559275cc61ec', '5559275cc61f2', 3, 'reviewer', 1,
> 0, '0000-00-00', '0000-00-00', 0, '', '0000-00-00 00:00:00', '2015-05-18
> 01:42:20', 'Reviewer/index.php');
>
> /
> *!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */; /*!40101
> SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS
> */; /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aisharaf/rms/issues/120>.
>



-- 

*Abd Elghafar M. Elhady*

*Lecturer, *

*Institute of Scientific Research and Revival of Islamic Heritage,*

*Umm Al-Qura Univearsity, KSA.*

**Comment by aisharaf** [comment]
https://gist.github.com/aisharaf/38bedcb9831add4ee913

**Comment by aisharaf** [comment]
http://sourceforge.net/projects/wampserver/files/latest/download

On Mon, May 18, 2015 at 1:44 PM, abdelghafar <notifications@github.com>
wrote:

> DROP TABLE IF EXISTS `reseach_status`;
> CREATE TABLE `reseach_status` (
> `Status_Id` int(11) NOT NULL auto_increment,
> `Status_name` varchar(100) NOT NULL,
> `Phase_id` int(2) NOT NULL,
> PRIMARY KEY (`Status_Id`)
> ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;
>
> --
> -- Dumping data for table `reseach_status`
> --
>
> INSERT INTO `reseach_status` VALUES (1, 'تم الاستلام', 1);
> INSERT INTO `reseach_status` VALUES (2, 'قيد الفحص', 1);
> INSERT INTO `reseach_status` VALUES (3, 'منجزة بالرفض', 1);
> INSERT INTO `reseach_status` VALUES (4, 'مقبول ومحال للتحكيم', 1);
> INSERT INTO `reseach_status` VALUES (5, 'قيد التحكيم', 2);
> INSERT INTO `reseach_status` VALUES (6, 'لا أوصي بالتمويل', 2);
> INSERT INTO `reseach_status` VALUES (7, 'أوصي بالتمويل دون أي تعديل', 2);
>
> -- --------------------------------------------------------
>
> --
> -- Table structure for table `sys_rules`
> --
>
> DROP TABLE IF EXISTS `sys_rules`;
> CREATE TABLE `sys_rules` (
> `rule_id` int(11) NOT NULL auto_increment,
> `rule_name` varchar(255) NOT NULL,
> `url` varchar(512) NOT NULL,
> `rule_desc` varchar(512) NOT NULL,
> PRIMARY KEY (`rule_id`)
> ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=9 ;
>
> --
> -- Dumping data for table `sys_rules`
> --
>
> INSERT INTO `sys_rules` VALUES (1, 'DSRDean', '', 'لوحة تحكم عمادة البحث
> العلمي');
> INSERT INTO `sys_rules` VALUES (2, 'DSRVIT', '', 'لوحة تحكم وكيل البحث
> العلمي للمعلومات');
> INSERT INTO `sys_rules` VALUES (3, 'DSRVPG', 'DSRVPG/index.php', 'لوحة تحكم
> وكيل البحث العلمي للمنح البحثية');
> INSERT INTO `sys_rules` VALUES (4, 'DSRVSC', '', 'لوحة تحكم وكيل البحث
> العلمي للكراسي العلمية');
> INSERT INTO `sys_rules` VALUES (5, 'DSRVSI', '', 'لوحة تحكم وكيل البحث
> العلمي للنزاهة العلمية');
> INSERT INTO `sys_rules` VALUES (6, 'DSRVFM', '', 'لوحة تحكم وكيل البحث
> العلمي شطر الطالبات');
> INSERT INTO `sys_rules` VALUES (7, 'DSRVPG_SupportTeam',
> 'DSRVPG_SupportTeam/index.php', 'لوحة تحكم فريق الدعم لوكيل البحث العلمي
> للمنح');
> INSERT INTO `sys_rules` VALUES (8, 'reviewer', 'Reviewer/index.php', 'لوحة
> تحكم المحكمين');
>
> -- --------------------------------------------------------
>
> --
> -- Table structure for table `users`
> --
>
> DROP TABLE IF EXISTS `users`;
> CREATE TABLE `users` (
> `id` int(11) NOT NULL auto_increment,
> `user_name` varchar(50) NOT NULL,
> `pass` varchar(100) NOT NULL,
> `activation_code` varchar(32) NOT NULL,
> `person_id` int(11) NOT NULL,
> `is_active` tinyint(1) NOT NULL,
> `sys_rule_id` int(2) NOT NULL,
> `from_date` date NOT NULL,
> `thru_date` date NOT NULL,
> `is_temp` tinyint(1) NOT NULL default '0',
> `alias_name` varchar(1024) NOT NULL,
> `last_access` datetime NOT NULL,
> `creation_date` datetime NOT NULL,
> PRIMARY KEY (`id`),
> UNIQUE KEY `user_name` (`user_name`)
> ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=20 ;
>
> --
> -- Dumping data for table `users`
> --
>
> INSERT INTO `users` VALUES (1, 'DSRDean@uqu.edu.sa', '', '', 0, 0, 1,
> '0000-00-00', '0000-00-00', 0, 'عميد البحث العلمي', '0000-00-00 00:00:00',
> '0000-00-00 00:00:00');
> INSERT INTO `users` VALUES (2, 'DSRVIT@uqu.edu.sa', '', '', 0, 0, 2,
> '0000-00-00', '0000-00-00', 0, 'وكيل عمادة البحث العلمي للمعلومات والنشر',
> '0000-00-00 00:00:00', '0000-00-00 00:00:00');
> INSERT INTO `users` VALUES (3, 'DSRVPG@uqu.edu.sa', '', '', 0, 0, 3,
> '0000-00-00', '0000-00-00', 0, 'وكيل عمادة البحث العلمي للمنح والمشاريع
> البحثيه', '0000-00-00 00:00:00', '0000-00-00 00:00:00');
> INSERT INTO `users` VALUES (4, 'DSRVSC@uqu.edu.sa', '', '', 0, 0, 4,
> '0000-00-00', '0000-00-00', 0, 'وكيل عمادة البحث العلمي للكراسي العلمية',
> '0000-00-00 00:00:00', '0000-00-00 00:00:00');
> INSERT INTO `users` VALUES (5, 'DSRVSI@uqu.edu.sa', '', '', 0, 0, 5,
> '0000-00-00', '0000-00-00', 0, 'وكيل عمادة البحث العلمي للنزاهه العلمية',
> '0000-00-00 00:00:00', '0000-00-00 00:00:00');
> INSERT INTO `users` VALUES (6, 'DSRVFM@uqu.edu.sa', '', '', 0, 0, 6,
> '0000-00-00', '0000-00-00', 0, 'وكيلة عمادة البحث العلمي لفرع الطالبات',
> '0000-00-00 00:00:00', '0000-00-00 00:00:00');
> INSERT INTO `users` VALUES (7, 'dsrmalesupport@uqu.edu.sa', '', '', 0, 0,
> 7, '0000-00-00', '0000-00-00', 0, 'الدعم الفني رجال', '0000-00-00
> 00:00:00', '0000-00-00 00:00:00');
> INSERT INTO `users` VALUES (8, 'dsrfemalesupport@uqu.edu.sa', '', '', 0,
> 0,
> 7, '0000-00-00', '0000-00-00', 0, 'الدعم الفني نساء', '0000-00-00
> 00:00:00', '0000-00-00 00:00:00');
> INSERT INTO `users` VALUES (19, 'aaaa@ddd.net', '5559275cc61ec',
> '5559275cc61f2', 3, 1, 8, '0000-00-00', '0000-00-00', 0, '', '0000-00-00
> 00:00:00', '2015-05-18 01:42:20');
>
>
> On Mon, May 18, 2015 at 11:15 AM, Ahmed I. Sharaf <
> notifications@github.com>
> wrote:
>
> > -- phpMyAdmin SQL Dump
> > -- version 4.1.14
> > -- http://www.phpmyadmin.net
> >
> > -- Host: 127.0.0.1
> > -- Generation Time: May 18, 2015 at 10:13 AM
> > -- Server version: 5.6.17
> > -- PHP Version: 5.5.12
> >
> > SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
> > SET time_zone = "+00:00";
> >
> > /
> > *!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */; /*!40101
> > SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS
> > */; /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION
> > */; /*!40101 SET NAMES utf8 */;
> > -- Database: dsr_rms
> > ------------------------------
> > -- Table structure for table users
> >
> > CREATE TABLE IF NOT EXISTS users (
> > id int(11) NOT NULL AUTO_INCREMENT,
> > user_name varchar(50) NOT NULL,
> > pass varchar(100) NOT NULL,
> > activation_code varchar(32) NOT NULL,
> > person_id int(11) NOT NULL,
> > rule varchar(20) NOT NULL,
> > is_active tinyint(1) NOT NULL,
> > sys_group_id int(2) NOT NULL,
> > from_date date NOT NULL,
> > thru_date date NOT NULL,
> > is_temp tinyint(1) NOT NULL DEFAULT '0',
> > alias_name varchar(1024) NOT NULL,
> > last_access datetime NOT NULL,
> > creation_date datetime NOT NULL,
> > url varchar(255) NOT NULL,
> > PRIMARY KEY (id),
> > UNIQUE KEY user_name (user_name)
> > ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=20 ;
> > -- Dumping data for table users
> >
> > INSERT INTO users (id, user_name, pass, activation_code, person_id, rule,
> > is_active, sys_group_id, from_date, thru_date, is_temp, alias_name,
> > last_access, creation_date, url) VALUES
> > (1, 'DSRDean@uqu.edu.sa', '', '', 0, 'DSRDean', 0, 0, '0000-00-00',
> > '0000-00-00', 0, 'عميد البحث العلمي', '0000-00-00 00:00:00', '0000-00-00
> > 00:00:00', ''),
> > (2, 'DSRVIT@uqu.edu.sa', '', '', 0, 'DSRVIT', 0, 0, '0000-00-00',
> > '0000-00-00', 0, 'وكيل عمادة البحث العلمي للمعلومات والنشر', '0000-00-00
> > 00:00:00', '0000-00-00 00:00:00', ''),
> > (3, 'DSRVPG@uqu.edu.sa', '', '', 0, 'DSRVPG', 0, 0, '0000-00-00',
> > '0000-00-00', 0, 'وكيل عمادة البحث العلمي للمنح والمشاريع البحثيه',
> > '0000-00-00 00:00:00', '0000-00-00 00:00:00', ''),
> > (4, 'DSRVSC@uqu.edu.sa', '', '', 0, 'DSRVSC', 0, 0, '0000-00-00',
> > '0000-00-00', 0, 'وكيل عمادة البحث العلمي للكراسي العلمية', '0000-00-00
> > 00:00:00', '0000-00-00 00:00:00', 'Administration'),
> > (5, 'DSRVSI@uqu.edu.sa', '', '', 0, 'DSRVSI', 0, 0, '0000-00-00',
> > '0000-00-00', 0, 'وكيل عمادة البحث العلمي للنزاهه العلمية', '0000-00-00
> > 00:00:00', '0000-00-00 00:00:00', ''),
> > (6, 'DSRVFM@uqu.edu.sa', '', '', 0, 'DSRVFM', 0, 0, '0000-00-00',
> > '0000-00-00', 0, 'وكيلة عمادة البحث العلمي لفرع الطالبات', '0000-00-00
> > 00:00:00', '0000-00-00 00:00:00', ''),
> > (7, 'dsrmalesupport@uqu.edu.sa', '', '', 0, 'DSRVPG', 0, 0,
> '0000-00-00',
> > '0000-00-00', 0, 'الدعم الفني رجال', '0000-00-00 00:00:00', '0000-00-00
> > 00:00:00', 'Administration'),
> > (8, 'dsrfemalesupport@uqu.edu.sa', '', '', 0, 'DSRVPG', 0, 0,
> > '0000-00-00', '0000-00-00', 0, 'الدعم الفني نساء', '0000-00-00 00:00:00',
> > '0000-00-00 00:00:00', ''),
> > (19, 'aaaa@ddd.net', '5559275cc61ec', '5559275cc61f2', 3, 'reviewer', 1,
> > 0, '0000-00-00', '0000-00-00', 0, '', '0000-00-00 00:00:00', '2015-05-18
> > 01:42:20', 'Reviewer/index.php');
> >
> > /
> > *!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */; /*!40101
> > SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS
> > */; /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/aisharaf/rms/issues/120>.
> >
>
>
>
> --
>
> *Abd Elghafar M. Elhady*
>
> *Lecturer, *
>
> *Institute of Scientific Research and Revival of Islamic Heritage,*
>
> *Umm Al-Qura Univearsity, KSA.*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aisharaf/rms/issues/120#issuecomment-103013646>.
>



-- 
______________________________________
Ahmed I. Sharaf

**Comment by abdelghafar** [comment]
---------- Forwarded message ----------
From: وكيل عمادة البحث العلمي للمعلومات والنشر <DSRVIT@uqu.edu.sa>
Date: Tue, Sep 15, 2015 at 10:00 AM
Subject: Fwd: محتوى غير مقروء
To: abdelghafar mohamed elhady <abdelghafar.elhady@gmail.com>




-------- Original message --------
From: وكيل عمادة البحث العلمي للمنح والمشاريع البحثيه <DSRVPG@uqu.edu.sa>
Date: 15/09/2015 8:51 am (GMT+03:00)
To: وكيل عمادة البحث العلمي للمعلومات والنشر <DSRVIT@uqu.edu.sa>
Subject: محتوى غير مقروء

السلام عليكم ورحمة الله،

لاحظت محتوى غير مقروء للمقدمة والمسح الادبي في الملف
http://dsr.uqu.edu.sa/rms/uploads/87/final_2015-09-09_e62d7f1eb43d87c202d2f164ba61297e71be80f4.pdf

هل السبب من رفع الملف او من الدمج؟ بمعنى هل الملف الذي تم رفعه للمقدمه
والاخر للمسح الادبي سليمين؟



شكرا.



------------------------------

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify Email System
Administrator (e_admin@uqu.edu.sa ) . Please note that any views or
opinions presented in this email are solely those of the author and do not
necessarily represent those of the Umm Al-Qura University. Finally, the
recipient should check this email and any attachments for the presence of
viruses. The Information Technology and Technical Support Center of Umm
Al-Qura University accepts no liability for any damage caused by any virus
transmitted by this email.



-- 

*Abd Elghafar M. Elhady*

*Lecturer, *

*Institute of Scientific Research and Revival of Islamic Heritage,*

*Umm Al-Qura Univearsity, KSA.*
