### ISSUE TITLE
make sitemap for research submit wizard or progress bar

### ISSUE THREAD

**Issue by aisharaf** [aisharaf/rms#25]

**Comment by aisharaf** [comment]
dear dr @aobaz  
![sample](https://cloud.githubusercontent.com/assets/418038/6695831/528bbcee-ccf5-11e4-915c-472e7646c3c7.png)

**Comment by aobaz** [comment]
I think the sitemap is good for now and it does the function. The next/previous buttons are good as well.

**Comment by abdelghafar** [comment]
done
