### ISSUE TITLE
About should be in every page and must contains

### ISSUE THREAD

**Issue by aobaz** [aisharaf/rms#38]
قامت عمادة البحث العلمي ممثلة في وكالة العمادة للمعلومات والنشر بتطوير هذا النظام تحت مسمى "نظام إدارة المنح البحثية" لمساعدة منسوبي جامعة أم القرى من أعضاء هيئة تدريس وباحثين على التقديم على منح مالية لدعم ابحاثهم.
تم تطوير هذا الموقع بالتعاون المشترك بين وكالة الجامعة للتطوير الأكاديمي وخدمة المجتمع ممثلة في عمادة تقنية المعلومات ووكالة الجامعة للدراسات العليا والبحث العلمي ممثلة في عمادة البحث العلمي. حيث وفرت عمادة تقنية المعلومات بيئة التطوير ورخص البرامج والخوادم وطرق الاتصال وقامت عمادة البحث العلمي بتحليل وتطوير الموقع.
قامت عمادة شئون أعضاء هيئة التدريس والموظفين مشكورة بالموافقة على الاتصال الرقمي بين النظام وبيانات أعضاء هيئة التدريس. الأمر الذي وفر على المتقدمين تسجيل بياناتهم الأساسية ووفر على عمادة البحث العلمي تدقيق تلك البيانات.
يقر فريق التحليل بعمادة البحث العلمي بأنه تمت الاستفادة من موقع الخطة الوطنية للعلوم والتقنية (nstip.kacst.edu.sa) خلال تطوير هذا الموقع.

**Comment by abdelghafar** [comment]
done
