### ISSUE TITLE
A fatal error

### ISSUE THREAD

**Issue by aobaz** [aisharaf/rms#48]
I edited project number 24 by removing the only CO-I. However, when I went to the "HR and tasks mapping" page, I found that the CO-I is still there and there are some tasks assigned to him. Ideally, all pages should read from the database, where relations should restrict the data integrity. I suppose when I remove a CO-I, his task mapping should be removed as well.
You've already considered this point in the "Project Budget" page.

**Comment by abdelghafar** [comment]
this error will be solved in next version of project team  (which include Research assistant)

**Comment by aisharaf** [comment]
fixed
