### ISSUE TITLE
don't forget the total and percentage for non manpower budget main categories

### ISSUE THREAD

**Issue by abdelghafar** [aisharaf/rms#5]

**Comment by abdelghafar** [comment]
I will do the same for manpower budget

**Comment by abdelghafar** [comment]
ADD the following function in (lib/budget.php) to get project total budget
public function GetBudgetTotal($projectId) {
        $conn = new MysqlConnect();
        $stmt = "SELECT sum(budget_amount) as project_budget FROM project_budget WHERE project_id=" . $projectId;
        $rs = $conn->ExecuteNonQuery($stmt);
        $row = mysql_fetch_array($rs);
        return $row['project_budget'];
    }

**Comment by abdelghafar** [comment]
Add the following functions in (rms/lib/budget.php)
to get project total budget and total budget for specific budget item 
public function GetBudgetTotal($projectId) {
        $conn = new MysqlConnect();
        $stmt = "SELECT sum(amount) as project_budget FROM project_budget WHERE project_id=" . $projectId;
        $rs = $conn->ExecuteNonQuery($stmt);
        $row = mysql_fetch_array($rs);
        return $row['project_budget'];
    }
    
    public function GetItemTotal($projectId,$item_id) {
        $conn = new MysqlConnect();
        $stmt = "SELECT sum(amount) as item_budget FROM project_budget WHERE project_id=" . $projectId. " AND item_id=" . $item_id;
        $rs = $conn->ExecuteNonQuery($stmt);
        $row = mysql_fetch_array($rs);
        return $row['item_budget'];
    }

**Comment by aisharaf** [comment]
As Soon As Possible
