### ISSUE TITLE
تغير الاولوية الي مجال البحث

### ISSUE THREAD

**Issue by aisharaf** [aisharaf/rms#50]

**Comment by aisharaf** [comment]
تغير كلمة نظام الي برنامج رائد

**Comment by aisharaf** [comment]
اضافة زر ابحاث سابك و المعلم محمد بن لادن

**Comment by aobaz** [comment]
ابحاث سابك
ابحاث مركز المعلم محمد بن لادن

**Comment by abdelghafar** [comment]
تم 
ويمكن الدخول الى برامج ابحاث سابك ومحمد بن لادن عن طريق الحساب التالي
amemohammed@uqu.edu.sa
ونفس كلمة مرور الحساب
aisharaf
