### ISSUE TITLE
وضع الأهداف الإستراتيجية في جدول (كالموجود في ربط الأهداف بالمراحل والمهام) ليسهل كتابتها عربي انجليزي

### ISSUE THREAD

**Issue by aobaz** [aisharaf/rms#62]
وضع الأهداف الإستراتيجية في جدول (كالموجود في ربط الأهداف بالمراحل والمهام) ليسهل كتابتها عربي انجليزي

**Comment by abdelghafar** [comment]
Done, Check it and Inform Us

**Comment by aobaz** [comment]
It is not working. I unchecked the goals and clicked close then next. However, the data was still there.

**Comment by abdelghafar** [comment]
i checked it now and it is working!!!!!!!!!!!!!!!!!!!!!!

what is the problem with it?????????????

**Comment by abdelghafar** [comment]
i tested it on firefox also and it is working
