### ISSUE TITLE
النسبة المئوية خانة من رقمين صحيحين ورقمين عشريين فقط. الرجاء فتح مشروعي المقدم في رائد نسبة ميزانية بند أخرى مكون من ثلاث أرقام صحيحة

### ISSUE THREAD

**Issue by aobaz** [aisharaf/rms#65]
النسبة المئوية خانة من رقمين صحيحين ورقمين عشريين فقط. الرجاء فتح مشروعي المقدم في رائد نسبة ميزانية بند أخرى مكون من ثلاث أرقام صحيحة

**Comment by aisharaf** [comment]
fixed
