### ISSUE TITLE
حساب النسبة المئوية غير صحيح. الرجاء فتح مشروعي المقدم في رائد: النسبة المواد يجب أن تكون 1.67 وليس 1.69. ونسبة الرحلات يجب أن تكون 1.84 وليس 1.69 ونسبة أخرى يجب أن تكون 0.67 وليس 677.97

### ISSUE THREAD

**Issue by aobaz** [aisharaf/rms#66]
حساب النسبة المئوية غير صحيح. الرجاء فتح مشروعي المقدم في رائد: النسبة المواد يجب أن تكون 1.67 وليس 1.69. ونسبة الرحلات يجب أن تكون 1.84 وليس 1.69 ونسبة أخرى يجب أن تكون 0.67 وليس 677.97

**Comment by aisharaf** [comment]
@aobaz  
we can not access ur account right now,
Please confirm us with print screen or your uqu account password

**Comment by aobaz** [comment]
I think you can, if you wish ;-)
Anyway, the proposal has been submitted and I cannot access it anymore. You can open the final pdf from the server.

**Comment by aisharaf** [comment]
what it the project title ?

**Comment by aobaz** [comment]
An open source tool for synthesizing and functional verification of asynchronous circuits
Moreover, you don't need to access it. Try a new project (the error should happen in all project)

**Comment by aisharaf** [comment]
it is okay

**Comment by aisharaf** [comment]
issue #66 is fixed
