### ISSUE TITLE
في ملف المقترح البحثي: جدول فريق العمل يظهر بدون بيانات وعناوين الجداول والحقول يجب أن تكون عربي انجليزي

### ISSUE THREAD

**Issue by aobaz** [aisharaf/rms#69]
في ملف المقترح البحثي: جدول فريق العمل يظهر بدون بيانات وعناوين الجداول والحقول يجب أن تكون عربي انجليزي

**Comment by abdelghafar** [comment]
generate arabic/ English pdf proposal

**Comment by abdelghafar** [comment]
Overcome on that comment in the new version of pdf
