### ISSUE TITLE
what about links in the home page (Upload files or Not)

### ISSUE THREAD

**Issue by abdelghafar** [aisharaf/rms#71]
like 
شروط التقديم
إجراءات تمويل المشاريع البحثية
...
where are the final edition of these files

**Comment by aobaz** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO Please

**Comment by abdelghafar** [comment]
OOOOOOOOOOOOOOOOKKKKKKKKKKKKKKKKYYYYYYYYY
