### ISSUE TITLE
شروط الدخول على البرامج

### ISSUE THREAD

**Issue by aobaz** [aisharaf/rms#82]
رائد متاح للذكور والاناث لمن هم/هن على وظيفة معيد (دون التقيد بتاريخ) ومحاضر (دون التقيد بتاريخ) واستاذ مساعد (اذا كان تاريخ فتح البرامج - تاريخ تعيينه اقل من 720 يوم)
باحث متاح للذكور لمن هم على وظيفة استاذ (دون التقيد بتاريخ) واستاذ مشارك (دون التقيد بتاريخ) واستاذ مساعد  (اذا كان تاريخ فتح البرامج - تاريخ تعيينه اكثر من 720 يوم)
واعدة متاح للاناث لمن هم على وظيفة استاذ (دون التقيد بتاريخ) واستاذ مشارك (دون التقيد بتاريخ) واستاذ مساعد  (اذا كان تاريخ فتح البرامج - تاريخ تعيينه اكثر من 720 يوم)

**Comment by aisharaf** [comment]
تاريخ التعين بالهجري 
@aobaz

**Comment by aisharaf** [comment]
@aobaz 
هل الجنسية عامل في التحويل الي البرامج ؟؟

**Comment by abdelghafar** [comment]
Done 
Need to be tested
@aobaz
